---

- name: Create stack user.
  user:
    name: stack
    comment: tripleo user
    shell: /bin/bash

- name: Add the sudoers config file.
  copy:
    src: stack
    dest: /etc/sudoers.d/stack
    owner: root
    group: root
    mode: '0440'
    validate: 'visudo -cf %s'

- name: Disable firewalld.
  service:
    name: firewalld
    state: stopped
    enabled: no

